const QUOTES = [
  { text: 'You do not rise to the level of your goals. You fall to the level of your systems.', author: 'James Clear' },
  { text: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', author: 'Will Durant' },
  { text: 'Success is the product of daily habits—not once-in-a-lifetime transformations.', author: 'James Clear' },
  { text: 'Motivation is what gets you started. Habit is what keeps you going.', author: 'Jim Ryun' },
  { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
  { text: 'Don’t break the chain.', author: 'Jerry Seinfeld' },
  { text: 'Small daily improvements over time lead to stunning results.', author: 'Robin Sharma' },
  { text: 'Discipline is choosing between what you want now and what you want most.', author: 'Abraham Lincoln' },
  { text: 'It’s not what we do once in a while that shapes our lives, but what we do consistently.', author: 'Tony Robbins' },
  { text: 'A year from now you may wish you had started today.', author: 'Karen Lamb' },
  { text: 'Every action you take is a vote for the type of person you wish to become.', author: 'James Clear' },
  { text: 'First we make our habits, then our habits make us.', author: 'Charles C. Noble' },
  { text: 'You’ll never change your life until you change something you do daily.', author: 'John C. Maxwell' },
  { text: 'The chains of habit are too weak to be felt until they are too strong to be broken.', author: 'Samuel Johnson' },
  { text: 'How you do anything is how you do everything.', author: 'T. Harv Eker' },
  { text: 'The best way to predict your future is to create it.', author: 'Abraham Lincoln' },
  { text: 'Do something today that your future self will thank you for.', author: 'Sean Patrick Flanery' },
  { text: 'Consistency is harder when no one is clapping for you. Clap for yourself.', author: 'Unknown' },
  { text: 'You don’t have to be great to start, but you have to start to be great.', author: 'Zig Ziglar' },
  { text: 'Lose an hour in the morning, and you will spend all day looking for it.', author: 'Richard Whately' },
  { text: 'Habits are the compound interest of self-improvement.', author: 'James Clear' },
  { text: 'What you do every day matters more than what you do once in a while.', author: 'Gretchen Rubin' },

  { text: 'The future depends on what you do today.', author: 'Mahatma Gandhi' },
  { text: 'Dream big. Start small. Act now.', author: 'Robin Sharma' },
  { text: 'Success is the sum of small efforts, repeated day in and day out.', author: 'Robert Collier' },
  { text: 'Little by little, a little becomes a lot.', author: 'Tanzanian Proverb' },
  { text: 'Action is the foundational key to all success.', author: 'Pablo Picasso' },
  { text: 'Well done is better than well said.', author: 'Benjamin Franklin' },
  { text: 'The journey of a thousand miles begins with one step.', author: 'Lao Tzu' },
  { text: 'Quality is not an act, it is a habit.', author: 'Aristotle' },
  { text: 'Great things are done by a series of small things brought together.', author: 'Vincent van Gogh' },
  { text: 'The difference between ordinary and extraordinary is that little extra.', author: 'Jimmy Johnson' },
  { text: 'Hard work beats talent when talent doesn’t work hard.', author: 'Tim Notke' },
  { text: 'Discipline equals freedom.', author: 'Jocko Willink' },
  { text: 'If you’re tired of starting over, stop giving up.', author: 'Unknown' },
  { text: 'Focus on being productive instead of busy.', author: 'Tim Ferriss' },
  { text: 'One day or day one. You decide.', author: 'Unknown' },
  { text: 'Progress, not perfection.', author: 'Unknown' },
  { text: 'Done is better than perfect.', author: 'Sheryl Sandberg' },
  { text: 'A little progress each day adds up to big results.', author: 'Satya Nani' },
  { text: 'Success doesn’t come from what you do occasionally. It comes from what you do consistently.', author: 'Marie Forleo' },
  { text: 'Fall in love with the process and the results will come.', author: 'Eric Thomas' },
  { text: 'The pain of discipline weighs ounces. The pain of regret weighs tons.', author: 'Jim Rohn' },
  { text: 'Discipline is remembering what you want.', author: 'David Campbell' },
  { text: 'Your habits will determine your future.', author: 'Jack Canfield' },
  { text: 'You become what you repeatedly practice.', author: 'Unknown' },
  { text: 'Small steps every day.', author: 'Unknown' },
  { text: 'Keep showing up.', author: 'Unknown' },
  { text: 'The only impossible journey is the one you never begin.', author: 'Tony Robbins' },
  { text: 'Success is earned daily.', author: 'Unknown' },
  { text: 'Your future is created by what you do today, not tomorrow.', author: 'Robert Kiyosaki' },
  { text: 'Be stronger than your excuses.', author: 'Unknown' },
  { text: 'The harder you work for something, the greater you’ll feel when you achieve it.', author: 'Unknown' },
  { text: 'Every accomplishment starts with the decision to try.', author: 'John F. Kennedy' },
  { text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe' },
  { text: 'Push yourself because no one else is going to do it for you.', author: 'Unknown' },
  { text: 'If it matters to you, you’ll find a way.', author: 'Charlie Gilkey' },
  { text: 'Make yourself proud.', author: 'Peter W. Smith' },
  { text: 'Stay patient and trust your journey.', author: 'Unknown' },
  { text: 'The expert in anything was once a beginner.', author: 'Helen Hayes' },
  { text: 'Be faithful to your daily routine.', author: 'Unknown' },
  { text: 'Consistency creates confidence.', author: 'Unknown' },
  { text: 'Every day is another chance to improve.', author: 'Unknown' },
  { text: 'Tiny gains become huge victories over time.', author: 'Unknown' },
  { text: 'The secret is consistency.', author: 'Unknown' },
  { text: 'One percent better every day.', author: 'James Clear' },
  { text: 'Don’t count the days. Make the days count.', author: 'Muhammad Ali' },
  { text: 'Nothing changes if nothing changes.', author: 'Unknown' },
  { text: 'Small disciplines repeated with consistency lead to great achievements.', author: 'John C. Maxwell' },
  { text: 'Your only competition is who you were yesterday.', author: 'Unknown' },
  { text: 'Keep your promises to yourself.', author: 'Unknown' },
  { text: 'You can’t improve what you don’t track.', author: 'Peter Drucker' },
  { text: 'Do the work even when you don’t feel like it.', author: 'Unknown' },
  { text: 'Success starts with self-discipline.', author: 'Unknown' },
  { text: 'The best investment you can make is in yourself.', author: 'Warren Buffett' },
  { text: 'Focus on progress, not applause.', author: 'Unknown' },
  { text: 'Every master was once a disaster.', author: 'T. Harv Eker' },
  { text: 'Never miss twice.', author: 'James Clear' },
  { text: 'Environment is the invisible hand that shapes behavior.', author: 'James Clear' },
  { text: 'Make the right thing easy.', author: 'James Clear' },
  { text: 'Every day is a fresh start.', author: 'Unknown' },
  { text: 'Discipline is self-respect in action.', author: 'Unknown' },
  { text: 'Your habits are writing your future story.', author: 'Unknown' },
  { text: 'Small wins build unstoppable momentum.', author: 'Unknown' },
  { text: 'Nothing worth having comes easy.', author: 'Theodore Roosevelt' },
  { text: 'Wake up with determination. Go to bed with satisfaction.', author: 'Unknown' },
  { text: 'Do what is right, not what is easy.', author: 'Roy T. Bennett' },
  { text: 'Work while they sleep. Learn while they party.', author: 'Unknown' },
  { text: 'Stay hungry. Stay foolish.', author: 'Steve Jobs' },
  { text: 'The only limit is the one you set yourself.', author: 'Unknown' },
  { text: 'Build habits, not wishes.', author: 'Unknown' },
  { text: 'Be addicted to bettering yourself.', author: 'Unknown' },
  { text: 'Your routine creates your reality.', author: 'Unknown' },
  { text: 'Success loves preparation.', author: 'Unknown' },
  { text: 'Every repetition makes you stronger.', author: 'Unknown' },
  { text: 'What gets measured gets managed.', author: 'Peter Drucker' },
  { text: 'Keep moving forward.', author: 'Walt Disney' },
  { text: 'It always seems impossible until it’s done.', author: 'Nelson Mandela' },
  { text: 'If you can dream it, you can do it.', author: 'Walt Disney' },
  { text: 'The key is not to prioritize what’s on your schedule, but to schedule your priorities.', author: 'Stephen Covey' },
  { text: 'The successful warrior is the average person with laser-like focus.', author: 'Bruce Lee' },
  { text: 'Don’t wish it were easier. Wish you were better.', author: 'Jim Rohn' },
  { text: 'Either you run the day or the day runs you.', author: 'Jim Rohn' },
  { text: 'Without commitment, you’ll never start. Without consistency, you’ll never finish.', author: 'Denzel Washington' },
  { text: 'Success is never owned. It is rented—and the rent is due every day.', author: 'Rory Vaden' },
  { text: 'Energy flows where attention goes.', author: 'Tony Robbins' },
  { text: 'You miss 100% of the shots you don’t take.', author: 'Wayne Gretzky' },
  { text: 'Believe you can and you’re halfway there.', author: 'Theodore Roosevelt' },
  { text: 'What we think, we become.', author: 'Buddha' },
  { text: 'Every day is an opportunity to become a better version of yourself.', author: 'Unknown' },
  { text: 'Keep planting seeds. The harvest will come.', author: 'Unknown' },
  { text: 'Your future self is watching.', author: 'Unknown' },
  { text: 'Start before you’re ready.', author: 'Steven Pressfield' },
  { text: 'Courage comes after action.', author: 'Unknown' },
  { text: 'Today’s effort is tomorrow’s success.', author: 'Unknown' },
  { text: 'A disciplined mind leads to a disciplined life.', author: 'Unknown' },
  { text: 'The strongest habits are built on the hardest days.', author: 'Unknown' },
  { text: 'Momentum beats motivation.', author: 'Unknown' },
  { text: 'Every repetition is a brick in your future.', author: 'Unknown' },
  { text: 'Be obsessed with improvement.', author: 'Unknown' },
  { text: 'Master the basics. Repeat forever.', author: 'Unknown' },
  { text: 'One good habit can change your life.', author: 'Unknown' },
  { text: 'Tiny actions. Massive outcomes.', author: 'Unknown' },
  { text: 'Consistency compounds.', author: 'Unknown' },
  { text: 'Your identity is shaped by your actions.', author: 'James Clear' },
  { text: 'Show up, even on the hard days.', author: 'Unknown' },
  { text: 'Win the morning. Win the day.', author: 'Tim Ferriss' },
  { text: 'Keep the promises you make to yourself.', author: 'Unknown' },
  { text: 'The best time to begin is now.', author: 'Unknown' },
  { text: 'Excellence grows from repetition.', author: 'Unknown' },
  { text: 'Don’t wait for inspiration. Create it through action.', author: 'Unknown' },
  { text: 'A disciplined life is a powerful life.', author: 'Unknown' },
  { text: 'Your daily choices become your destiny.', author: 'Unknown' },
  { text: 'Success is built one day at a time.', author: 'Unknown' },
  { text: 'The goal is to become better than yesterday.', author: 'Unknown' },
  { text: 'Every day counts.', author: 'Unknown' }
];

// Deterministic quote of the day so it stays stable all day.
export function quoteOfTheDay(dateKey) {
  let hash = 0
  for (let i = 0; i < dateKey.length; i++) {
    hash = (hash * 31 + dateKey.charCodeAt(i)) >>> 0
  }
  return QUOTES[hash % QUOTES.length]
}

export default QUOTES
